### ISSUE TITLE
Property tests don't get garbage collected

### ISSUE THREAD

**Issue by Theodus** [mfelsche/ponycheck#31]
This loop (and the inner loop for shrinking) occur within a single `ponytest` actor behavior without the ability to perform GC:
https://github.com/mfelsche/ponycheck/blob/be1e5be80952cb6972c26e93b0091ed156bf81ff/ponycheck/property.pony#L76

The only way to solve this without separating from ponytest entirely would be to offload these loops into recursive behaviors on another actor. There are two options that I have run into while trying to resolve this:
1. Make `Generator` and `PropertyParams` have `val` capabilities and make the property method of the `Property1` trait return a lambda `val` or `iso` as the property so that these values can be sent to another actor.
2. Leave the `Property1` trait as it is, make it `iso`, and separate it from `UnitTest` so that it can be handed to a custom `UnitTest` constructor that handles the test in an actor. This would make the user define the `TestList` entry for a `Property1` like this:
    ```pony
    actor Main is TestList
      ...
      fun tag tests(test: PonyTest) =>
        test(Prop1[Array[USize]](_ListReverseProperty))
    ```

I personally prefer the second option, but there may be a better way that I have not considered.

**Comment by mfelsche** [comment]
I am also in favor of version 2 as this leaves the api that is visible to the user as is (besides the change in the TestList definition) and it also has the beneficial side effect that we get rid of issue #28 and we can start implementing asynchronous properties with this setup, having a separate actor handling the property.

Concerning the API change for compatibility with PonyTest, maybe even something like this is possible:

```pony
actor Main is TestList
  fun tag tests(test: PonyTest) =>
    test(_ListReverseProperty.asUnitTest())
```

but this could bring us back to having to import stuff when implementing properties.
