### ISSUE TITLE
Shrinking results appear old/off-by-one?/wrong

### ISSUE THREAD

**Issue by slfritchie** [mfelsche/ponycheck#36]
I've been writing a step-by-step experience of creating a Ponycheck test for a new data structure for Wallaroo, the `HashPartition`, see https://github.com/slfritchie/wallaroo/blob/e69307f/lib/wallaroo/core/routing/hash_partitions.pony

I was using https://gist.github.com/slfritchie/0f37815b75b6a54a4885b5c19649782e for the Ponycheck test.  As written, I expect a failing test case almost all the time, because the functions under test will raise error (e.g. removing a set member that was not added, adding or removing the same member twice).  However, this failure case is not expected: no ops at all:

    Params(seed=1380414927) Run(0) /Users/scott/src/study/hash_partitions/_test.pony:399: Assert true passed. 
    add failed
    add failed
    remove failed
    remove failed
    Params(seed=1380414927) Shrink(3) /Users/scott/src/study/hash_partitions/_test.pony:399: Assert true passed. 
    Property failed for sample [] (after 3 shrinks)
    Complete(false) called

This case shouldn't be an error(i.e., simply adding a member a single time):

    **** FAILED: hash_partitions/ponycheck
    remove failed
    add failed
    Params(seed=1380458117) Shrink(1) /Users/scott/src/study/hash_partitions/_test.pony:399: Assert true passed. 
    Property failed for sample [
      op=add_claimants,cs=[n2]] (after 1 shrinks)
    Complete(false) called

It seems as if the "Property failed for sample" is likely from another shrinking attempt rather than the case that actually fails?

I used `git bisect` to see if the reports changed from accurate-seeming to looks-bad.  The result was:

    a0d3685ae60bc94efa603e09efe137167ac7cf7c is the first bad commit
    commit a0d3685ae60bc94efa603e09efe137167ac7cf7c
    Author: Matthias Wahl <mfelsche@users.noreply.github.com>
    Date:   Wed Mar 14 14:58:09 2018 +0100
    
        Enable asynchronous properties (#35)
        
       [...]
    
    :040000 040000 ab74d63988bc791af69d2f09e51cc51c04f1617a cd9070835a76a046b0dcae546e26ff8369e28a73 M	examples
    :040000 040000 7a240bfab855a7b485b58a0d6115c18e2dae3a87 45332574437b009c5db5d6b94553a180852943bf M	ponycheck

**Comment by mfelsche** [comment]
Thanks for this detailed reporting and doing the git bisect dance. I spotted the error, it is in PropertyRunner.complete_shrink

Unfortunately i will only be able to fix this by next week.

**Comment by mfelsche** [comment]
I will also fix Generators.one_of to have a non-partial version. :)
